services:
  xray-checker:
    image: kutovoys/xray-checker
    container_name: xray-checker
    restart: always
    networks:
      - xray-sp-network
    environment:
      - SUBSCRIPTION_URL=CHANGE_ME
      - PROXY_CHECK_INTERVAL=30
      - PROXY_CHECK_METHOD=status
      - PROXY_STATUS_CHECK_URL="http://cp.cloudflare.com/generate_204"
      - PROXY_TIMEOUT=15
      - SIMULATE_LATENCY=false
      - WEB_PUBLIC=false
      - METRICS_PROTECTED=true
      - METRICS_USERNAME=CHANGE_ME
      - METRICS_PASSWORD=CHANGE_ME

  xray-sp:
    image: ghcr.io/kastov/xray-sp:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: xray-sp
    restart: always
    networks:
      - xray-sp-network
    depends_on:
      - xray-checker
    environment:
      - POLL_INTERVAL=30
      - DAYS=30
      - TZ=Europe/Moscow
      # Change these before exposing /admin:
      - ADMIN_USERNAME=CHANGE_ME
      - ADMIN_PASSWORD=CHANGE_ME
    volumes:
      - xray-sp-db-data:/data
    ports:
      - "127.0.0.1:8080:8080"

volumes:
  xray-sp-db-data:
    name: xray-sp-db-data
    driver: local
    external: false

networks:
  xray-sp-network:
    name: xray-sp-network
    driver: bridge
    external: false
