// Country dataset for detecting a server's country from its display name.
// `kw` are lowercase keyword fragments (countries + major cities) in English
// and Russian. All keywords are >= 3 chars; bare 2-letter ISO codes are matched
// separately as standalone tokens (see geo.ts) to avoid false substring hits.

export interface Country {
  /** ISO 3166-1 alpha-2, lowercase. */
  cc: string;
  kw: string[];
}

export const COUNTRIES: Country[] = [
  { cc: 'nl', kw: ['netherlands', 'netherland', 'holland', 'amsterdam', 'нидерланд', 'голланд', 'амстердам'] },
  { cc: 'de', kw: ['germany', 'deutschland', 'deutsch', 'frankfurt', 'berlin', 'munich', 'герман', 'франкфурт', 'берлин', 'мюнхен'] },
  { cc: 'fi', kw: ['finland', 'helsinki', 'финлянд', 'хельсинки'] },
  { cc: 'us', kw: ['united states', 'usa', 'u.s.a', 'america', 'american', 'new york', 'los angeles', 'san jose', 'san francisco', 'miami', 'dallas', 'seattle', 'chicago', 'ashburn', 'atlanta', 'indiana', 'indianapolis', 'сша', 'америк', 'нью-йорк', 'нью йорк', 'майами', 'даллас', 'сиэтл', 'чикаго'] },
  { cc: 'gb', kw: ['united kingdom', 'britain', 'british', 'england', 'london', 'великобритан', 'британ', 'англия', 'лондон'] },
  { cc: 'fr', kw: ['france', 'french', 'paris', 'marseille', 'франц', 'париж', 'марсель'] },
  { cc: 'jp', kw: ['japan', 'japanese', 'tokyo', 'osaka', 'япон', 'токио', 'осака'] },
  { cc: 'sg', kw: ['singapore', 'сингапур'] },
  { cc: 'tr', kw: ['turkey', 'turkiye', 'türkiye', 'turkish', 'istanbul', 'турц', 'турк', 'стамбул'] },
  { cc: 'ru', kw: ['russia', 'russian', 'moscow', 'saint petersburg', 'st petersburg', 'росси', 'москва', 'питер', 'санкт-петербург', 'спб', 'екатеринбург', 'новосибирск'] },
  { cc: 'pl', kw: ['poland', 'polish', 'warsaw', 'польш', 'варшава'] },
  { cc: 'se', kw: ['sweden', 'swedish', 'stockholm', 'швец', 'швеци', 'стокгольм'] },
  { cc: 'ch', kw: ['switzerland', 'swiss', 'zurich', 'geneva', 'швейцар', 'цюрих', 'женева'] },
  { cc: 'ca', kw: ['canada', 'canadian', 'toronto', 'montreal', 'vancouver', 'канад', 'торонто', 'монреаль', 'ванкувер'] },
  { cc: 'it', kw: ['italy', 'italia', 'italian', 'milan', 'milano', 'rome', 'roma', 'naples', 'napoli', 'turin', 'torino', 'venice', 'venezia', 'итал', 'милан', 'рим', 'неапол', 'турин', 'венеци'] },
  { cc: 'es', kw: ['spain', 'spanish', 'espana', 'españa', 'madrid', 'barcelona', 'испан', 'мадрид', 'барселон'] },
  { cc: 'hk', kw: ['hong kong', 'hongkong', 'гонконг'] },
  { cc: 'kr', kw: ['korea', 'korean', 'seoul', 'корея', 'корей', 'сеул'] },
  { cc: 'in', kw: ['india', 'indian', 'mumbai', 'delhi', 'инди', 'мумбаи', 'дели'] },
  { cc: 'at', kw: ['austria', 'vienna', 'австри', 'вена'] },
  { cc: 'no', kw: ['norway', 'oslo', 'норвег', 'осло'] },
  { cc: 'dk', kw: ['denmark', 'copenhagen', 'дани', 'копенгаген'] },
  { cc: 'ie', kw: ['ireland', 'dublin', 'ирланд', 'дублин'] },
  { cc: 'cz', kw: ['czech', 'czechia', 'prague', 'чех', 'чехи', 'прага'] },
  { cc: 'ua', kw: ['ukraine', 'ukrainian', 'kyiv', 'kiev', 'украин', 'киев', 'харьков'] },
  { cc: 'ae', kw: ['emirates', 'united arab', 'dubai', 'abu dhabi', 'оаэ', 'эмират', 'дубай'] },
  { cc: 'il', kw: ['israel', 'tel aviv', 'израил', 'тель-авив', 'тель авив'] },
  { cc: 'br', kw: ['brazil', 'brasil', 'sao paulo', 'бразил', 'сан-паулу'] },
  { cc: 'au', kw: ['australia', 'sydney', 'melbourne', 'австрал', 'сидней', 'мельбурн'] },
  { cc: 'cn', kw: ['china', 'chinese', 'shanghai', 'beijing', 'китай', 'кита', 'шанхай', 'пекин'] },
  { cc: 'hu', kw: ['hungary', 'budapest', 'венгр', 'будапешт'] },
  { cc: 'ro', kw: ['romania', 'bucharest', 'румын', 'бухарест'] },
  { cc: 'bg', kw: ['bulgaria', 'sofia', 'болгар', 'софия'] },
  { cc: 'lv', kw: ['latvia', 'riga', 'латви', 'рига'] },
  { cc: 'lt', kw: ['lithuania', 'vilnius', 'литва', 'литов', 'вильнюс'] },
  { cc: 'ee', kw: ['estonia', 'tallinn', 'эстони', 'таллин'] },
  { cc: 'kz', kw: ['kazakhstan', 'almaty', 'astana', 'казахстан', 'алматы', 'астана'] },
  { cc: 'ge', kw: ['georgia', 'tbilisi', 'груз', 'грузи', 'тбилиси'] },
  { cc: 'am', kw: ['armenia', 'yerevan', 'армени', 'ереван'] },
  { cc: 'az', kw: ['azerbaijan', 'baku', 'азербайджан', 'баку'] },
  { cc: 'rs', kw: ['serbia', 'belgrade', 'серб', 'серби', 'белград'] },
  { cc: 'gr', kw: ['greece', 'athens', 'греци', 'афины'] },
  { cc: 'pt', kw: ['portugal', 'lisbon', 'португал', 'лиссабон'] },
  { cc: 'be', kw: ['belgium', 'brussels', 'бельги', 'брюссель'] },
  { cc: 'mx', kw: ['mexico', 'мексик', 'мехико'] },
  { cc: 'ar', kw: ['argentina', 'buenos aires', 'аргентин', 'буэнос-айрес'] },
  { cc: 'za', kw: ['south africa', 'johannesburg', 'юар', 'южная африка', 'йоханнесбург'] },
  { cc: 'id', kw: ['indonesia', 'jakarta', 'индонез', 'джакарта'] },
  { cc: 'th', kw: ['thailand', 'bangkok', 'таиланд', 'тайланд', 'бангкок'] },
  { cc: 'vn', kw: ['vietnam', 'hanoi', 'вьетнам', 'ханой'] },
  { cc: 'my', kw: ['malaysia', 'kuala lumpur', 'малайз', 'куала-лумпур'] },
  { cc: 'ph', kw: ['philippines', 'manila', 'филиппин', 'манила'] },
  { cc: 'sa', kw: ['saudi', 'riyadh', 'саудов', 'эр-рияд'] },
  { cc: 'cy', kw: ['cyprus', 'кипр'] },
  { cc: 'is', kw: ['iceland', 'reykjavik', 'исланд', 'рейкьявик'] },
  { cc: 'sk', kw: ['slovakia', 'bratislava', 'словаки', 'братислава'] },
  { cc: 'si', kw: ['slovenia', 'ljubljana', 'словени', 'любляна'] },
  { cc: 'hr', kw: ['croatia', 'zagreb', 'хорват', 'загреб'] },
  { cc: 'md', kw: ['moldova', 'chisinau', 'молдов', 'кишинёв', 'кишинев'] },
  { cc: 'by', kw: ['belarus', 'minsk', 'беларус', 'белорус', 'минск'] },
  { cc: 'uz', kw: ['uzbekistan', 'tashkent', 'узбекистан', 'ташкент'] },
  { cc: 'lu', kw: ['luxembourg', 'люксембург'] },
  { cc: 'tw', kw: ['taiwan', 'taipei', 'тайвань', 'тайбэй'] },
  { cc: 'al', kw: ['albania', 'tirana', 'албани', 'тирана'] },
  { cc: 'mk', kw: ['macedonia', 'skopje', 'македони', 'скопье'] },
  { cc: 'ba', kw: ['bosnia', 'sarajevo', 'босни', 'сараево'] },
  { cc: 'me', kw: ['montenegro', 'podgorica', 'черногори', 'подгорица'] },
  { cc: 'mt', kw: ['malta', 'мальт'] },
  { cc: 'eg', kw: ['egypt', 'cairo', 'египет', 'каир'] },
  { cc: 'ng', kw: ['nigeria', 'lagos', 'нигери', 'лагос'] },
  { cc: 'ke', kw: ['kenya', 'nairobi', 'кени', 'найроби'] },
  { cc: 'cl', kw: ['chile', 'santiago', 'чили', 'сантьяго'] },
  { cc: 'co', kw: ['colombia', 'bogota', 'колумби', 'богота'] },
  { cc: 'pe', kw: ['peru', 'lima', 'перу', 'лима'] },
  { cc: 'pk', kw: ['pakistan', 'karachi', 'пакистан', 'карачи'] },
  { cc: 'bd', kw: ['bangladesh', 'dhaka', 'бангладеш', 'дакка'] },
  { cc: 'ir', kw: ['iran', 'tehran', 'иран', 'тегеран'] },
  { cc: 'iq', kw: ['iraq', 'baghdad', 'ирак', 'багдад'] },
  { cc: 'qa', kw: ['qatar', 'doha', 'катар', 'доха'] },
  { cc: 'kw', kw: ['kuwait', 'кувейт'] },
  { cc: 'bh', kw: ['bahrain', 'бахрейн'] },
  { cc: 'jo', kw: ['jordan', 'amman', 'иордани', 'амман'] },
  { cc: 'lb', kw: ['lebanon', 'beirut', 'ливан', 'бейрут'] },
  { cc: 'np', kw: ['nepal', 'kathmandu', 'непал', 'катманду'] },
  { cc: 'lk', kw: ['sri lanka', 'colombo', 'шри-ланка', 'коломбо'] },
  { cc: 'nz', kw: ['new zealand', 'auckland', 'новая зеланди', 'окленд'] },
];

/** Set of valid ISO alpha-2 codes for standalone-token detection. */
export const ISO_CODES: Set<string> = new Set(COUNTRIES.map((c) => c.cc));
